services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz_php
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: quiz_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: quiz_user
      MYSQL_PASSWORD: quiz_pass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: quiz_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: quiz_user
      PMA_PASSWORD: quiz_pass
    ports:
      - "8080:80"
    depends_on:
      - db

  node:
    image: node:22
    container_name: quiz_react
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: tail -f /dev/null
    ports:
      - "5173:5173"

volumes:
  db-data: